#!/bin/bash
##
##check if mfsmaster is accessable.
##if not return 1,else return 0
###################################################################


if [ `/etc/init.d/mfsmaster status | grep -c running` -eq 0 ];then
	exit 1
fi

exit 0
