#!/bin/bash
##
##check if tomcat is alive.
##if not return 1 ,else return 0
###############################################################



if [ `/etc/init.d/mysql status | grep -c running` -eq 0 ];then
	exit 1
else
	exit 0
fi
