#!/bin/bash
##
##check if nginx is accessable.
##if not return 1,else return 0
################################################################


if [ `/etc/init.d/nginx status | grep -c running`  -eq 0 ];then
	exit 1
else
	exit 0
fi



